### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by RaptaG** [ReviversMC/advanced-tooltips#11]
🙏🏽

**Comment by sternschnaube** [comment]
Hello, I would love to use the mod on 1.19.3 as well.
**Here is the crash log:**

java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'advanced-tooltips'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at fudge.notenoughcrashes.fabric.mixinhandlers.ModLoaders.fabricEntrypoints(ModLoaders.java:9)
	at net.minecraft.class_310.redirect$gnb000$catchFabricInit(class_310.java:31480)
	at net.minecraft.class_310.<init>(class_310.java:465)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchFieldError: field_25108
	at com.github.reviversmc.advancedtooltips.AdvancedTooltips.<clinit>(AdvancedTooltips.java:62)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 10 more

**Comment by NebelNidas** [comment]
Yeah, I'll have to port it first, hopefully it'll be finished around next week

**Comment by Vi-Tul** [comment]
Any updates?

**Comment by RaptaG** [comment]
@NebelNidas 
> Yeah, I'll have to port it first, hopefully it'll be finished around next week

Well it's been quite some time after _next week_. Could you please port it, I mean the commit on the official exists..
